package com.squaresaresquare.github.block.entity;

import com.squaresaresquare.github.block.entity.custom.doublewindowarch.*;
import com.squaresaresquare.github.block.entity.custom.mosaic.MosaicA1BlockEntity;
import com.squaresaresquare.github.block.entity.custom.quadruplewindowarch.*;
import com.squaresaresquare.github.block.entity.custom.simplearchedwindow.*;
import com.squaresaresquare.github.block.entity.custom.triplewindowarch.*;
import com.squaresaresquare.github.block.entity.custom.mosaic.*;
import net.fabricmc.fabric.api.object.builder.v1.block.entity.FabricBlockEntityTypeBuilder;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import org.jetbrains.annotations.NotNull;
import com.squaresaresquare.github.ArchitectureBlocks;
import com.squaresaresquare.github.block.ModBlocks;
import com.squaresaresquare.github.block.entity.custom.*;

public class ModBlockEntities {
    private static <T extends BlockEntity> BlockEntityType<@NotNull T> register(
            String name,
            FabricBlockEntityTypeBuilder.Factory<? extends T> entityFactory,
            Block... blocks
    ) {
        Identifier id = Identifier.fromNamespaceAndPath(ArchitectureBlocks.MOD_ID, name);

        return Registry.register(BuiltInRegistries.BLOCK_ENTITY_TYPE, id, FabricBlockEntityTypeBuilder.<T>create(entityFactory, blocks).build());
    }
    public static void initialize() {
        System.out.print("initialize ModBlockEntities\n");
    }
    public static final BlockEntityType<@NotNull OakLogBlockEntity> OAK_LOG_BLOCK_ENTITY = register("oak_log", OakLogBlockEntity::new, ModBlocks.OAK_LOG);
    public static final BlockEntityType<@NotNull CircleCornerBlockEntity> CIRCLE_CORNER_BLOCK_ENTITY = register("circle_corner", CircleCornerBlockEntity::new, ModBlocks.CIRCLE_CORNER);
    public static final BlockEntityType<@NotNull QuartzCircleCornerBlockEntity> QUARTZ_CIRCLE_CORNER_BLOCK_ENTITY = register("quartz_circle_corner", QuartzCircleCornerBlockEntity::new, ModBlocks.QUARTZ_CIRCLE_CORNER);
    public static final BlockEntityType<@NotNull WhiteConcreteCircleCornerBlockEntity> WHITE_CONCRETE_CIRCLE_CORNER_BLOCK_ENTITY = register("white_concrete_circle_corner", WhiteConcreteCircleCornerBlockEntity::new, ModBlocks.WHITE_CONCRETE_CIRCLE_CORNER);
    public static final BlockEntityType<@NotNull MarbleBlockBlockEntity> MARBLE_BLOCK_BLOCK_ENTITY = register("marble_block", MarbleBlockBlockEntity::new, ModBlocks.MARBLE_BLOCK);
    public static final BlockEntityType<@NotNull MarblePillarBaseBlockEntity> MARBLE_PILLAR_BASE_BLOCK_ENTITY = register("marble_pillar_base", MarblePillarBaseBlockEntity::new, ModBlocks.MARBLE_PILLAR_BASE);
    public static final BlockEntityType<@NotNull MarblePillarBlockEntity> MARBLE_PILLAR_BLOCK_ENTITY = register("marble_pillar", MarblePillarBlockEntity::new, ModBlocks.MARBLE_PILLAR);
    public static final BlockEntityType<@NotNull MarblePlinthBlockEntity> MARBLE_PLINTH_BLOCK_ENTITY = register("quartz_pillar", MarblePlinthBlockEntity::new, ModBlocks.MARBLE_PLINTH_BLOCK);
    public static final BlockEntityType<@NotNull PillarCapBlockEntity> PILLAR_CAP_BLOCK_ENTITY = register("pillar_cap", PillarCapBlockEntity::new, ModBlocks.PILLAR_CAP);
    public static final BlockEntityType<@NotNull LeftEndBaseBlockEntity> LEFT_END_BASE_BLOCK_ENTITY = register("left_end_base", LeftEndBaseBlockEntity::new, ModBlocks.LEFT_END_BASE);
    public static final BlockEntityType<@NotNull LeftPillarBaseBlockEntity> LEFT_PILLAR_BASE_BLOCK_ENTITY = register("left_pillar_base", LeftPillarBaseBlockEntity::new, ModBlocks.LEFT_PILLAR_BASE);
    public static final BlockEntityType<@NotNull RightPillarBaseBlockEntity> RIGHT_PILLAR_BASE_BLOCK_ENTITY = register("right_pillar_base", RightPillarBaseBlockEntity::new, ModBlocks.RIGHT_PILLAR_BASE);
    public static final BlockEntityType<@NotNull RightEndBaseBlockEntity> RIGHT_END_BASE_BLOCK_ENTITY = register("right_end_base", RightEndBaseBlockEntity::new, ModBlocks.RIGHT_END_BASE);
    public static final BlockEntityType<@NotNull LeftEndMiddleBlockEntity> LEFT_END_MIDDLE_BLOCK_ENTITY = register("left_end_middle", LeftEndMiddleBlockEntity::new, ModBlocks.LEFT_END_MIDDLE);
    public static final BlockEntityType<@NotNull LeftPillarMiddleBlockEntity> LEFT_PILLAR_MIDDLE_BLOCK_ENTITY = register("left_pillar_middle", LeftPillarMiddleBlockEntity::new, ModBlocks.LEFT_PILLAR_MIDDLE);
    public static final BlockEntityType<@NotNull RightPillarMiddleBlockEntity> RIGHT_PILLAR_MIDDLE_BLOCK_ENTITY = register("right_pillar_middle", RightPillarMiddleBlockEntity::new, ModBlocks.RIGHT_PILLAR_MIDDLE);
    public static final BlockEntityType<@NotNull RightEndMiddleBlockEntity> RIGHT_END_MIDDLE_BLOCK_ENTITY = register("right_end_middle", RightEndMiddleBlockEntity::new, ModBlocks.RIGHT_END_MIDDLE);
    public static final BlockEntityType<@NotNull TripleWindowArchRow1Col1BlockEntity> TRIPLE_WINDOW_ARCH_ROW1_COL1_BLOCK_ENTITY = register("triple_window_arch_row1_col1", TripleWindowArchRow1Col1BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW1_COL1);
    public static final BlockEntityType<@NotNull LeftEndCapBlockEntity> LEFT_END_CAP_BLOCK_ENTITY = register("left_end_cap", LeftEndCapBlockEntity::new, ModBlocks.LEFT_END_CAP);
    public static final BlockEntityType<@NotNull LeftPillarCapBlockEntity> LEFT_PILLAR_CAP_BLOCK_ENTITY = register("left_pillar_cap", LeftPillarCapBlockEntity::new, ModBlocks.LEFT_PILLAR_CAP);
    public static final BlockEntityType<@NotNull RightPillarCapBlockEntity> RIGHT_PILLAR_CAP_BLOCK_ENTITY = register("right_pillar_cap", RightPillarCapBlockEntity::new, ModBlocks.RIGHT_PILLAR_CAP);
    public static final BlockEntityType<@NotNull RightEndCapBlockEntity> RIGHT_END_CAP_BLOCK_ENTITY = register("right_end_cap", RightEndCapBlockEntity::new, ModBlocks.RIGHT_END_CAP);
    public static final BlockEntityType<@NotNull TripleWindowArchRow1Col6BlockEntity> TRIPLE_WINDOW_ARCH_ROW1_COL6_BLOCK_ENTITY = register("triple_window_arch_row1_col6", TripleWindowArchRow1Col6BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW1_COL6);
    public static final BlockEntityType<@NotNull TripleWindowArchRow2Col1BlockEntity> TRIPLE_WINDOW_ARCH_ROW2_COL1_BLOCK_ENTITY = register("triple_window_arch_row2_col1", TripleWindowArchRow2Col1BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW2_COL1);
    public static final BlockEntityType<@NotNull TripleWindowArchRow2Col2BlockEntity> TRIPLE_WINDOW_ARCH_ROW2_COL2_BLOCK_ENTITY = register("triple_window_arch_row2_col2", TripleWindowArchRow2Col2BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW2_COL2);
    public static final BlockEntityType<@NotNull TripleWindowArchRow2Col5BlockEntity> TRIPLE_WINDOW_ARCH_ROW2_COL5_BLOCK_ENTITY = register("triple_window_arch_row2_col5", TripleWindowArchRow2Col5BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW2_COL5);
    public static final BlockEntityType<@NotNull TripleWindowArchRow2Col6BlockEntity> TRIPLE_WINDOW_ARCH_ROW2_COL6_BLOCK_ENTITY = register("triple_window_arch_row2_col6", TripleWindowArchRow2Col6BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW2_COL6);
    public static final BlockEntityType<@NotNull TripleWindowArchRow4Col1BlockEntity> TRIPLE_WINDOW_ARCH_ROW4_COL1_BLOCK_ENTITY = register("triple_window_arch_row4_col1", TripleWindowArchRow4Col1BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW4_COL1);
    public static final BlockEntityType<@NotNull TripleWindowArchRow4Col2BlockEntity> TRIPLE_WINDOW_ARCH_ROW4_COL2_BLOCK_ENTITY = register("triple_window_arch_row4_col2", TripleWindowArchRow4Col2BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW4_COL2);
    public static final BlockEntityType<@NotNull TripleWindowArchRow4Col3BlockEntity> TRIPLE_WINDOW_ARCH_ROW4_COL3_BLOCK_ENTITY = register("triple_window_arch_row4_col3", TripleWindowArchRow4Col3BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW4_COL3);
    public static final BlockEntityType<@NotNull TripleWindowArchRow4Col4BlockEntity> TRIPLE_WINDOW_ARCH_ROW4_COL4_BLOCK_ENTITY = register("triple_window_arch_row4_col4", TripleWindowArchRow4Col4BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW4_COL4);
    public static final BlockEntityType<@NotNull TripleWindowArchRow4Col5BlockEntity> TRIPLE_WINDOW_ARCH_ROW4_COL5_BLOCK_ENTITY = register("triple_window_arch_row4_col5", TripleWindowArchRow4Col5BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW4_COL5);
    public static final BlockEntityType<@NotNull TripleWindowArchRow4Col6BlockEntity> TRIPLE_WINDOW_ARCH_ROW4_COL6_BLOCK_ENTITY = register("triple_window_arch_row4_col6", TripleWindowArchRow4Col6BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW4_COL6);
    public static final BlockEntityType<@NotNull TripleWindowArchRow5Col2BlockEntity> TRIPLE_WINDOW_ARCH_ROW5_COL2_BLOCK_ENTITY = register("triple_window_arch_row5_col2", TripleWindowArchRow5Col2BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW5_COL2);
    public static final BlockEntityType<@NotNull TripleWindowArchRow5Col3BlockEntity> TRIPLE_WINDOW_ARCH_ROW5_COL3_BLOCK_ENTITY = register("triple_window_arch_row5_col3", TripleWindowArchRow5Col3BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW5_COL3);
    public static final BlockEntityType<@NotNull TripleWindowArchRow5Col4BlockEntity> TRIPLE_WINDOW_ARCH_ROW5_COL4_BLOCK_ENTITY = register("triple_window_arch_row5_col4", TripleWindowArchRow5Col4BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW5_COL4);
    public static final BlockEntityType<@NotNull TripleWindowArchRow5Col5BlockEntity> TRIPLE_WINDOW_ARCH_ROW5_COL5_BLOCK_ENTITY = register("triple_window_arch_row5_col5", TripleWindowArchRow5Col5BlockEntity::new, ModBlocks.TRIPLE_WINDOW_ARCH_ROW5_COL5);
    public static final BlockEntityType<@NotNull RightHalfPillarBaseBlockEntity> RIGHT_HALF_PILLAR_BASE_BLOCK_ENTITY = register("right_half_pillar_base", RightHalfPillarBaseBlockEntity::new, ModBlocks.RIGHT_HALF_PILLAR_BASE);
    public static final BlockEntityType<@NotNull RightHalfPillarCapBlockEntity> RIGHT_HALF_PILLAR_CAP_BLOCK_ENTITY = register("right_half_pillar_cap", RightHalfPillarCapBlockEntity::new, ModBlocks.RIGHT_HALF_PILLAR_CAP);
    public static final BlockEntityType<@NotNull RightHalfPillarMiddleBlockEntity> RIGHT_HALF_PILLAR_MIDDLE_BLOCK_ENTITY = register("right_half_pillar_middle", RightHalfPillarMiddleBlockEntity::new, ModBlocks.RIGHT_HALF_PILLAR_MIDDLE);
    public static final BlockEntityType<@NotNull LeftHalfPillarBaseBlockEntity> LEFT_HALF_PILLAR_BASE_BLOCK_ENTITY = register("left_half_pillar_base", LeftHalfPillarBaseBlockEntity::new, ModBlocks.LEFT_HALF_PILLAR_BASE);
    public static final BlockEntityType<@NotNull LeftHalfPillarCapBlockEntity> LEFT_HALF_PILLAR_CAP_BLOCK_ENTITY = register("left_half_pillar_cap", LeftHalfPillarCapBlockEntity::new, ModBlocks.LEFT_HALF_PILLAR_CAP);
    public static final BlockEntityType<@NotNull LeftHalfPillarMiddleBlockEntity> LEFT_HALF_PILLAR_MIDDLE_BLOCK_ENTITY = register("left_half_pillar_middle", LeftHalfPillarMiddleBlockEntity::new, ModBlocks.LEFT_HALF_PILLAR_MIDDLE);
    public static final BlockEntityType<@NotNull CenterPillarBaseBlockEntity> CENTER_PILLAR_BASE_BLOCK_ENTITY = register("center_pillar_base", CenterPillarBaseBlockEntity::new, ModBlocks.CENTER_PILLAR_BASE);
    public static final BlockEntityType<@NotNull CenterPillarMiddleBlockEntity> CENTER_PILLAR_MIDDLE_BLOCK_ENTITY = register("center_pillar_middle", CenterPillarMiddleBlockEntity::new, ModBlocks.CENTER_PILLAR_MIDDLE);
    public static final BlockEntityType<@NotNull CenterPillarCapBlockEntity> CENTER_PILLAR_CAP_BLOCK_ENTITY = register("center_pillar_cap", CenterPillarCapBlockEntity::new, ModBlocks.CENTER_PILLAR_CAP);
    public static final BlockEntityType<@NotNull CenterCornerPillarBaseBlockEntity> CENTER_CORNER_PILLAR_BASE_BLOCK_ENTITY = register("center_corner_pillar_base", CenterCornerPillarBaseBlockEntity::new, ModBlocks.CENTER_CORNER_PILLAR_BASE);
    public static final BlockEntityType<@NotNull CenterCornerPillarMiddleBlockEntity> CENTER_CORNER_PILLAR_MIDDLE_BLOCK_ENTITY = register("center_corner_pillar_middle", CenterCornerPillarMiddleBlockEntity::new, ModBlocks.CENTER_CORNER_PILLAR_MIDDLE);
    public static final BlockEntityType<@NotNull CenterCornerPillarCapBlockEntity> CENTER_CORNER_PILLAR_CAP_BLOCK_ENTITY = register("center_corner_pillar_cap", CenterCornerPillarCapBlockEntity::new, ModBlocks.CENTER_CORNER_PILLAR_CAP);
    public static final BlockEntityType<@NotNull CornerWindowBaseBlockEntity> CORNER_WINDOW_BASE_BLOCK_ENTITY = register("corner_window_base", CornerWindowBaseBlockEntity::new, ModBlocks.CORNER_WINDOW_BASE);
    public static final BlockEntityType<@NotNull CornerWindowMiddleBlockEntity> CORNER_WINDOW_MIDDLE_BLOCK_ENTITY = register("corner_window_middle", CornerWindowMiddleBlockEntity::new, ModBlocks.CORNER_WINDOW_MIDDLE);
    public static final BlockEntityType<@NotNull CornerWindowCapBlockEntity> CORNER_WINDOW_CAP_BLOCK_ENTITY = register("corner_window_cap", CornerWindowCapBlockEntity::new, ModBlocks.CORNER_WINDOW_CAP);
    public static final BlockEntityType<@NotNull SlotWindowBaseBlockEntity> SLOT_WINDOW_BASE_BLOCK_ENTITY = register("slot_window_base", SlotWindowBaseBlockEntity::new, ModBlocks.SLOT_WINDOW_BASE);
    public static final BlockEntityType<@NotNull SlotWindowMiddleBlockEntity> SLOT_WINDOW_MIDDLE_BLOCK_ENTITY = register("slot_window_middle", SlotWindowMiddleBlockEntity::new, ModBlocks.SLOT_WINDOW_MIDDLE);
    public static final BlockEntityType<@NotNull SlotWindowCapBlockEntity> SLOT_WINDOW_CAP_BLOCK_ENTITY = register("slot_window_cap", SlotWindowCapBlockEntity::new, ModBlocks.SLOT_WINDOW_CAP);
    public static final BlockEntityType<@NotNull PillarlessWindowBaseBlockEntity> PILLARLESS_WINDOW_BASE_BLOCK_ENTITY = register("pillarless_window_base", PillarlessWindowBaseBlockEntity::new, ModBlocks.PILLARLESS_WINDOW_BASE);
    public static final BlockEntityType<@NotNull PillarlessWindowMiddleBlockEntity> PILLARLESS_WINDOW_MIDDLE_BLOCK_ENTITY = register("pillarless_window_middle", PillarlessWindowMiddleBlockEntity::new, ModBlocks.PILLARLESS_WINDOW_MIDDLE);
    public static final BlockEntityType<@NotNull PillarlessWindowCapBlockEntity> PILLARLESS_WINDOW_CAP_BLOCK_ENTITY = register("pillarless_window_cap", PillarlessWindowCapBlockEntity::new, ModBlocks.PILLARLESS_WINDOW_CAP);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow1Col1BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW1_COL1_BLOCK_ENTITY = register("quadruple_window_arch_row1_col1", QuadrupleWindowArchRow1Col1BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW1_COL1);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow1Col8BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW1_COL8_BLOCK_ENTITY = register("quadruple_window_arch_row1_col8", QuadrupleWindowArchRow1Col8BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW1_COL8);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow2Col1BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW2_COL1_BLOCK_ENTITY = register("quadruple_window_arch_row2_col1", QuadrupleWindowArchRow2Col1BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW2_COL1);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow2Col8BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW2_COL8_BLOCK_ENTITY = register("quadruple_window_arch_row2_col8", QuadrupleWindowArchRow2Col8BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW2_COL8);
    public static final BlockEntityType<@NotNull InnerArchBlockBlockEntity> INNER_ARCH_BLOCK_BLOCK_ENTITY = register("inner_arch_block", InnerArchBlockBlockEntity::new, ModBlocks.INNER_ARCH_BLOCK);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow2Col2BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW2_COL2_BLOCK_ENTITY = register("quadruple_window_arch_row2_col2", QuadrupleWindowArchRow2Col2BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW2_COL2);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow2Col7BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW2_COL7_BLOCK_ENTITY = register("quadruple_window_arch_row2_col7", QuadrupleWindowArchRow2Col7BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW2_COL7);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow3Col1BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW3_COL1_BLOCK_ENTITY = register("quadruple_window_arch_row3_col1", QuadrupleWindowArchRow3Col1BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW3_COL1);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow3Col2BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW3_COL2_BLOCK_ENTITY = register("quadruple_window_arch_row3_col2", QuadrupleWindowArchRow3Col2BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW3_COL2);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow3Col3BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW3_COL3_BLOCK_ENTITY = register("quadruple_window_arch_row3_col3", QuadrupleWindowArchRow3Col3BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW3_COL3);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow3Col6BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW3_COL6_BLOCK_ENTITY = register("quadruple_window_arch_row3_col6", QuadrupleWindowArchRow3Col6BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW3_COL6);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow3Col7BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW3_COL7_BLOCK_ENTITY = register("quadruple_window_arch_row3_col7", QuadrupleWindowArchRow3Col7BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW3_COL7);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow3Col8BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW3_COL8_BLOCK_ENTITY = register("quadruple_window_arch_row3_col8", QuadrupleWindowArchRow3Col8BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW3_COL8);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow1Col2BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW1_COL2_BLOCK_ENTITY = register("quadruple_window_arch_row1_col2", QuadrupleWindowArchRow1Col2BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW1_COL2);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow1Col3BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW1_COL3_BLOCK_ENTITY = register("quadruple_window_arch_row1_col3", QuadrupleWindowArchRow1Col3BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW1_COL3);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow1Col4BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW1_COL4_BLOCK_ENTITY = register("quadruple_window_arch_row1_col4", QuadrupleWindowArchRow1Col4BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW1_COL4);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow1Col5BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW1_COL5_BLOCK_ENTITY = register("quadruple_window_arch_row1_col5", QuadrupleWindowArchRow1Col5BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW1_COL5);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow1Col6BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW1_COL6_BLOCK_ENTITY = register("quadruple_window_arch_row1_col6", QuadrupleWindowArchRow1Col6BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW1_COL6);
    public static final BlockEntityType<@NotNull QuadrupleWindowArchRow1Col7BlockEntity> QUADRUPLE_WINDOW_ARCH_ROW1_COL7_BLOCK_ENTITY = register("quadruple_window_arch_row1_col7", QuadrupleWindowArchRow1Col7BlockEntity::new, ModBlocks.QUADRUPLE_WINDOW_ARCH_ROW1_COL7);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow1Col1BlockEntity> DOUBLE_WINDOW_ARCH_ROW1_COL1_BLOCK_ENTITY = register("double_window_arch_row1_col1", DoubleWindowArchRow1Col1BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW1_COL1);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow1Col4BlockEntity> DOUBLE_WINDOW_ARCH_ROW1_COL4_BLOCK_ENTITY = register("double_window_arch_row1_col4", DoubleWindowArchRow1Col4BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW1_COL4);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow1Col5BlockEntity> DOUBLE_WINDOW_ARCH_ROW1_COL5_BLOCK_ENTITY = register("double_window_arch_row1_col5", DoubleWindowArchRow1Col5BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW1_COL5);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow1Col2BlockEntity> DOUBLE_WINDOW_ARCH_ROW1_COL2_BLOCK_ENTITY = register("double_window_arch_row1_col2", DoubleWindowArchRow1Col2BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW1_COL2);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow2Col1BlockEntity> DOUBLE_WINDOW_ARCH_ROW2_COL1_BLOCK_ENTITY = register("double_window_arch_row2_col1", DoubleWindowArchRow2Col1BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW2_COL1);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow2Col2BlockEntity> DOUBLE_WINDOW_ARCH_ROW2_COL2_BLOCK_ENTITY = register("double_window_arch_row2_col2", DoubleWindowArchRow2Col2BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW2_COL2);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow2Col3BlockEntity> DOUBLE_WINDOW_ARCH_ROW2_COL3_BLOCK_ENTITY = register("double_window_arch_row2_col3", DoubleWindowArchRow2Col3BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW2_COL3);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow2Col4BlockEntity> DOUBLE_WINDOW_ARCH_ROW2_COL4_BLOCK_ENTITY = register("double_window_arch_row2_col4", DoubleWindowArchRow2Col4BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW2_COL4);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow2Col5BlockEntity> DOUBLE_WINDOW_ARCH_ROW2_COL5_BLOCK_ENTITY = register("double_window_arch_row2_col5", DoubleWindowArchRow2Col5BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW2_COL5);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow3Col2BlockEntity> DOUBLE_WINDOW_ARCH_ROW3_COL2_BLOCK_ENTITY = register("double_window_arch_row3_col2", DoubleWindowArchRow3Col2BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW3_COL2);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow3Col3BlockEntity> DOUBLE_WINDOW_ARCH_ROW3_COL3_BLOCK_ENTITY = register("double_window_arch_row3_col3", DoubleWindowArchRow3Col3BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW3_COL3);
    public static final BlockEntityType<@NotNull DoubleWindowArchRow3Col4BlockEntity> DOUBLE_WINDOW_ARCH_ROW3_COL4_BLOCK_ENTITY = register("double_window_arch_row3_col4", DoubleWindowArchRow3Col4BlockEntity::new, ModBlocks.DOUBLE_WINDOW_ARCH_ROW3_COL4);
    public static final BlockEntityType<@NotNull WindowBlankEntity> WINDOW_BLANK_ENTITY = register("window_blank", WindowBlankEntity::new, ModBlocks.WINDOW_BLANK);
    public static final BlockEntityType<@NotNull HayBlockEntity> HAY_BLOCK_ENTITY = register("hay_block", HayBlockEntity::new, ModBlocks.HAY_BLOCK);
    public static final BlockEntityType<@NotNull ThatchBlockEntity> THATCH_BLOCK_ENTITY = register("thatch", ThatchBlockEntity::new, ModBlocks.THATCH_BLOCK);
    public static final BlockEntityType<@NotNull ThatchPeakBlockEntity> THATCH_PEAK_BLOCK_ENTITY = register("thatch_peak", ThatchPeakBlockEntity::new, ModBlocks.THATCH_PEAK_BLOCK);
    public static final BlockEntityType<@NotNull SimpleArchedWindowTopLeftBlockEntity> SIMPLE_ARCHED_WINDOW_TOP_LEFT_BLOCK_ENTITY = register("simple_arched_window_top_left", SimpleArchedWindowTopLeftBlockEntity::new, ModBlocks.SIMPLE_ARCHED_WINDOW_TOP_LEFT);
    public static final BlockEntityType<@NotNull SimpleArchedWindowTopRightBlockEntity> SIMPLE_ARCHED_WINDOW_TOP_RIGHT_BLOCK_ENTITY = register("simple_arched_window_top_right", SimpleArchedWindowTopRightBlockEntity::new, ModBlocks.SIMPLE_ARCHED_WINDOW_TOP_RIGHT);
    public static final BlockEntityType<@NotNull SimpleArchedWindowTopCenterBlockEntity> SIMPLE_ARCHED_WINDOW_TOP_CENTER_BLOCK_ENTITY = register("simple_arched_window_top_center", SimpleArchedWindowTopCenterBlockEntity::new, ModBlocks.SIMPLE_ARCHED_WINDOW_TOP_CENTER);
    public static final BlockEntityType<@NotNull SimpleArchedWindowTopBetweenBlockEntity> SIMPLE_ARCHED_WINDOW_TOP_BETWEEN_BLOCK_ENTITY = register("simple_arched_window_top_between", SimpleArchedWindowTopBetweenBlockEntity::new, ModBlocks.SIMPLE_ARCHED_WINDOW_TOP_BETWEEN);
    public static final BlockEntityType<@NotNull SimpleArchedWindowLeftBlockEntity> SIMPLE_ARCHED_WINDOW_LEFT_BLOCK_ENTITY = register("simple_arched_window_left", SimpleArchedWindowLeftBlockEntity::new, ModBlocks.SIMPLE_ARCHED_WINDOW_LEFT);
    public static final BlockEntityType<@NotNull SimpleArchedWindowRightBlockEntity> SIMPLE_ARCHED_WINDOW_RIGHT_BLOCK_ENTITY = register("simple_arched_window_right", SimpleArchedWindowRightBlockEntity::new, ModBlocks.SIMPLE_ARCHED_WINDOW_RIGHT);
    public static final BlockEntityType<@NotNull SimpleArchedWindowBetweenBlockEntity> SIMPLE_ARCHED_WINDOW_BETWEEN_BLOCK_ENTITY = register("simple_arched_window_between", SimpleArchedWindowBetweenBlockEntity::new, ModBlocks.SIMPLE_ARCHED_WINDOW_BETWEEN);
    public static final BlockEntityType<@NotNull CrownMoldingRightBlockEntity> CROWN_MOLDING_RIGHT_BLOCK_ENTITY = register("crown_molding_right", CrownMoldingRightBlockEntity::new, ModBlocks.CROWN_MOLDING_RIGHT);
    public static final BlockEntityType<@NotNull CrownMoldingLeftBlockEntity> CROWN_MOLDING_LEFT_BLOCK_ENTITY = register("crown_molding_left", CrownMoldingLeftBlockEntity::new, ModBlocks.CROWN_MOLDING_LEFT);

    public static final BlockEntityType<@NotNull WhiteConcreteKeyholeBlockEntity> WHITE_CONCRETE_KEYHOLE_BLOCK_ENTITY = register("white_concrete_keyhole", WhiteConcreteKeyholeBlockEntity::new, ModBlocks.WHITE_CONCRETE_KEYHOLE_BLOCK);
    public static final BlockEntityType<@NotNull PolishedDioriteKeyholeBlockEntity> POLISHED_DIORITE_KEYHOLE_BLOCK_ENTITY = register("polished_diorite_keyhole", PolishedDioriteKeyholeBlockEntity::new, ModBlocks.POLISHED_DIORITE_KEYHOLE_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA1BlockEntity> MOSAIC_A1_BLOCK_ENTITY = register("a1", MosaicA1BlockEntity::new, ModBlocks.MOSAIC_A1_BLOCK);

    public static final BlockEntityType<@NotNull MosaicA2BlockEntity> MOSAIC_A2_BLOCK_ENTITY = register("a2", MosaicA2BlockEntity::new, ModBlocks.MOSAIC_A2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA3BlockEntity> MOSAIC_A3_BLOCK_ENTITY = register("a3", MosaicA3BlockEntity::new, ModBlocks.MOSAIC_A3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA4BlockEntity> MOSAIC_A4_BLOCK_ENTITY = register("a4", MosaicA4BlockEntity::new, ModBlocks.MOSAIC_A4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA5BlockEntity> MOSAIC_A5_BLOCK_ENTITY = register("a5", MosaicA5BlockEntity::new, ModBlocks.MOSAIC_A5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA6BlockEntity> MOSAIC_A6_BLOCK_ENTITY = register("a6", MosaicA6BlockEntity::new, ModBlocks.MOSAIC_A6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA7BlockEntity> MOSAIC_A7_BLOCK_ENTITY = register("a7", MosaicA7BlockEntity::new, ModBlocks.MOSAIC_A7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA8BlockEntity> MOSAIC_A8_BLOCK_ENTITY = register("a8", MosaicA8BlockEntity::new, ModBlocks.MOSAIC_A8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA9BlockEntity> MOSAIC_A9_BLOCK_ENTITY = register("a9", MosaicA9BlockEntity::new, ModBlocks.MOSAIC_A9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA10BlockEntity> MOSAIC_A10_BLOCK_ENTITY = register("a10", MosaicA10BlockEntity::new, ModBlocks.MOSAIC_A10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA11BlockEntity> MOSAIC_A11_BLOCK_ENTITY = register("a11", MosaicA11BlockEntity::new, ModBlocks.MOSAIC_A11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicA12BlockEntity> MOSAIC_A12_BLOCK_ENTITY = register("a12", MosaicA12BlockEntity::new, ModBlocks.MOSAIC_A12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB1BlockEntity> MOSAIC_B1_BLOCK_ENTITY = register("b1", MosaicB1BlockEntity::new, ModBlocks.MOSAIC_B1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB2BlockEntity> MOSAIC_B2_BLOCK_ENTITY = register("b2", MosaicB2BlockEntity::new, ModBlocks.MOSAIC_B2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB3BlockEntity> MOSAIC_B3_BLOCK_ENTITY = register("b3", MosaicB3BlockEntity::new, ModBlocks.MOSAIC_B3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB4BlockEntity> MOSAIC_B4_BLOCK_ENTITY = register("b4", MosaicB4BlockEntity::new, ModBlocks.MOSAIC_B4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB5BlockEntity> MOSAIC_B5_BLOCK_ENTITY = register("b5", MosaicB5BlockEntity::new, ModBlocks.MOSAIC_B5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB6BlockEntity> MOSAIC_B6_BLOCK_ENTITY = register("b6", MosaicB6BlockEntity::new, ModBlocks.MOSAIC_B6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB7BlockEntity> MOSAIC_B7_BLOCK_ENTITY = register("b7", MosaicB7BlockEntity::new, ModBlocks.MOSAIC_B7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB8BlockEntity> MOSAIC_B8_BLOCK_ENTITY = register("b8", MosaicB8BlockEntity::new, ModBlocks.MOSAIC_B8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB9BlockEntity> MOSAIC_B9_BLOCK_ENTITY = register("b9", MosaicB9BlockEntity::new, ModBlocks.MOSAIC_B9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB10BlockEntity> MOSAIC_B10_BLOCK_ENTITY = register("b10", MosaicB10BlockEntity::new, ModBlocks.MOSAIC_B10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB11BlockEntity> MOSAIC_B11_BLOCK_ENTITY = register("b11", MosaicB11BlockEntity::new, ModBlocks.MOSAIC_B11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicB12BlockEntity> MOSAIC_B12_BLOCK_ENTITY = register("b12", MosaicB12BlockEntity::new, ModBlocks.MOSAIC_B12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC1BlockEntity> MOSAIC_C1_BLOCK_ENTITY = register("c1", MosaicC1BlockEntity::new, ModBlocks.MOSAIC_C1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC2BlockEntity> MOSAIC_C2_BLOCK_ENTITY = register("c2", MosaicC2BlockEntity::new, ModBlocks.MOSAIC_C2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC3BlockEntity> MOSAIC_C3_BLOCK_ENTITY = register("c3", MosaicC3BlockEntity::new, ModBlocks.MOSAIC_C3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC4BlockEntity> MOSAIC_C4_BLOCK_ENTITY = register("c4", MosaicC4BlockEntity::new, ModBlocks.MOSAIC_C4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC5BlockEntity> MOSAIC_C5_BLOCK_ENTITY = register("c5", MosaicC5BlockEntity::new, ModBlocks.MOSAIC_C5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC6BlockEntity> MOSAIC_C6_BLOCK_ENTITY = register("c6", MosaicC6BlockEntity::new, ModBlocks.MOSAIC_C6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC7BlockEntity> MOSAIC_C7_BLOCK_ENTITY = register("c7", MosaicC7BlockEntity::new, ModBlocks.MOSAIC_C7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC8BlockEntity> MOSAIC_C8_BLOCK_ENTITY = register("c8", MosaicC8BlockEntity::new, ModBlocks.MOSAIC_C8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC9BlockEntity> MOSAIC_C9_BLOCK_ENTITY = register("c9", MosaicC9BlockEntity::new, ModBlocks.MOSAIC_C9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC10BlockEntity> MOSAIC_C10_BLOCK_ENTITY = register("c10", MosaicC10BlockEntity::new, ModBlocks.MOSAIC_C10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC11BlockEntity> MOSAIC_C11_BLOCK_ENTITY = register("c11", MosaicC11BlockEntity::new, ModBlocks.MOSAIC_C11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicC12BlockEntity> MOSAIC_C12_BLOCK_ENTITY = register("c12", MosaicC12BlockEntity::new, ModBlocks.MOSAIC_C12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD1BlockEntity> MOSAIC_D1_BLOCK_ENTITY = register("d1", MosaicD1BlockEntity::new, ModBlocks.MOSAIC_D1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD2BlockEntity> MOSAIC_D2_BLOCK_ENTITY = register("d2", MosaicD2BlockEntity::new, ModBlocks.MOSAIC_D2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD3BlockEntity> MOSAIC_D3_BLOCK_ENTITY = register("d3", MosaicD3BlockEntity::new, ModBlocks.MOSAIC_D3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD4BlockEntity> MOSAIC_D4_BLOCK_ENTITY = register("d4", MosaicD4BlockEntity::new, ModBlocks.MOSAIC_D4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD5BlockEntity> MOSAIC_D5_BLOCK_ENTITY = register("d5", MosaicD5BlockEntity::new, ModBlocks.MOSAIC_D5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD6BlockEntity> MOSAIC_D6_BLOCK_ENTITY = register("d6", MosaicD6BlockEntity::new, ModBlocks.MOSAIC_D6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD7BlockEntity> MOSAIC_D7_BLOCK_ENTITY = register("d7", MosaicD7BlockEntity::new, ModBlocks.MOSAIC_D7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD8BlockEntity> MOSAIC_D8_BLOCK_ENTITY = register("d8", MosaicD8BlockEntity::new, ModBlocks.MOSAIC_D8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD9BlockEntity> MOSAIC_D9_BLOCK_ENTITY = register("d9", MosaicD9BlockEntity::new, ModBlocks.MOSAIC_D9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD10BlockEntity> MOSAIC_D10_BLOCK_ENTITY = register("d10", MosaicD10BlockEntity::new, ModBlocks.MOSAIC_D10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD11BlockEntity> MOSAIC_D11_BLOCK_ENTITY = register("d11", MosaicD11BlockEntity::new, ModBlocks.MOSAIC_D11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicD12BlockEntity> MOSAIC_D12_BLOCK_ENTITY = register("d12", MosaicD12BlockEntity::new, ModBlocks.MOSAIC_D12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE1BlockEntity> MOSAIC_E1_BLOCK_ENTITY = register("e1", MosaicE1BlockEntity::new, ModBlocks.MOSAIC_E1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE2BlockEntity> MOSAIC_E2_BLOCK_ENTITY = register("e2", MosaicE2BlockEntity::new, ModBlocks.MOSAIC_E2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE3BlockEntity> MOSAIC_E3_BLOCK_ENTITY = register("e3", MosaicE3BlockEntity::new, ModBlocks.MOSAIC_E3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE4BlockEntity> MOSAIC_E4_BLOCK_ENTITY = register("e4", MosaicE4BlockEntity::new, ModBlocks.MOSAIC_E4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE5BlockEntity> MOSAIC_E5_BLOCK_ENTITY = register("e5", MosaicE5BlockEntity::new, ModBlocks.MOSAIC_E5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE6BlockEntity> MOSAIC_E6_BLOCK_ENTITY = register("e6", MosaicE6BlockEntity::new, ModBlocks.MOSAIC_E6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE7BlockEntity> MOSAIC_E7_BLOCK_ENTITY = register("e7", MosaicE7BlockEntity::new, ModBlocks.MOSAIC_E7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE8BlockEntity> MOSAIC_E8_BLOCK_ENTITY = register("e8", MosaicE8BlockEntity::new, ModBlocks.MOSAIC_E8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE9BlockEntity> MOSAIC_E9_BLOCK_ENTITY = register("e9", MosaicE9BlockEntity::new, ModBlocks.MOSAIC_E9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE10BlockEntity> MOSAIC_E10_BLOCK_ENTITY = register("e10", MosaicE10BlockEntity::new, ModBlocks.MOSAIC_E10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE11BlockEntity> MOSAIC_E11_BLOCK_ENTITY = register("e11", MosaicE11BlockEntity::new, ModBlocks.MOSAIC_E11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicE12BlockEntity> MOSAIC_E12_BLOCK_ENTITY = register("e12", MosaicE12BlockEntity::new, ModBlocks.MOSAIC_E12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF1BlockEntity> MOSAIC_F1_BLOCK_ENTITY = register("f1", MosaicF1BlockEntity::new, ModBlocks.MOSAIC_F1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF2BlockEntity> MOSAIC_F2_BLOCK_ENTITY = register("f2", MosaicF2BlockEntity::new, ModBlocks.MOSAIC_F2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF3BlockEntity> MOSAIC_F3_BLOCK_ENTITY = register("f3", MosaicF3BlockEntity::new, ModBlocks.MOSAIC_F3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF4BlockEntity> MOSAIC_F4_BLOCK_ENTITY = register("f4", MosaicF4BlockEntity::new, ModBlocks.MOSAIC_F4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF5BlockEntity> MOSAIC_F5_BLOCK_ENTITY = register("f5", MosaicF5BlockEntity::new, ModBlocks.MOSAIC_F5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF6BlockEntity> MOSAIC_F6_BLOCK_ENTITY = register("f6", MosaicF6BlockEntity::new, ModBlocks.MOSAIC_F6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF7BlockEntity> MOSAIC_F7_BLOCK_ENTITY = register("f7", MosaicF7BlockEntity::new, ModBlocks.MOSAIC_F7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF8BlockEntity> MOSAIC_F8_BLOCK_ENTITY = register("f8", MosaicF8BlockEntity::new, ModBlocks.MOSAIC_F8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF9BlockEntity> MOSAIC_F9_BLOCK_ENTITY = register("f9", MosaicF9BlockEntity::new, ModBlocks.MOSAIC_F9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF10BlockEntity> MOSAIC_F10_BLOCK_ENTITY = register("f10", MosaicF10BlockEntity::new, ModBlocks.MOSAIC_F10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF11BlockEntity> MOSAIC_F11_BLOCK_ENTITY = register("f11", MosaicF11BlockEntity::new, ModBlocks.MOSAIC_F11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicF12BlockEntity> MOSAIC_F12_BLOCK_ENTITY = register("f12", MosaicF12BlockEntity::new, ModBlocks.MOSAIC_F12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG1BlockEntity> MOSAIC_G1_BLOCK_ENTITY = register("g1", MosaicG1BlockEntity::new, ModBlocks.MOSAIC_G1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG2BlockEntity> MOSAIC_G2_BLOCK_ENTITY = register("g2", MosaicG2BlockEntity::new, ModBlocks.MOSAIC_G2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG3BlockEntity> MOSAIC_G3_BLOCK_ENTITY = register("g3", MosaicG3BlockEntity::new, ModBlocks.MOSAIC_G3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG4BlockEntity> MOSAIC_G4_BLOCK_ENTITY = register("g4", MosaicG4BlockEntity::new, ModBlocks.MOSAIC_G4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG5BlockEntity> MOSAIC_G5_BLOCK_ENTITY = register("g5", MosaicG5BlockEntity::new, ModBlocks.MOSAIC_G5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG6BlockEntity> MOSAIC_G6_BLOCK_ENTITY = register("g6", MosaicG6BlockEntity::new, ModBlocks.MOSAIC_G6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG7BlockEntity> MOSAIC_G7_BLOCK_ENTITY = register("g7", MosaicG7BlockEntity::new, ModBlocks.MOSAIC_G7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG8BlockEntity> MOSAIC_G8_BLOCK_ENTITY = register("g8", MosaicG8BlockEntity::new, ModBlocks.MOSAIC_G8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG9BlockEntity> MOSAIC_G9_BLOCK_ENTITY = register("g9", MosaicG9BlockEntity::new, ModBlocks.MOSAIC_G9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG10BlockEntity> MOSAIC_G10_BLOCK_ENTITY = register("g10", MosaicG10BlockEntity::new, ModBlocks.MOSAIC_G10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG11BlockEntity> MOSAIC_G11_BLOCK_ENTITY = register("g11", MosaicG11BlockEntity::new, ModBlocks.MOSAIC_G11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicG12BlockEntity> MOSAIC_G12_BLOCK_ENTITY = register("g12", MosaicG12BlockEntity::new, ModBlocks.MOSAIC_G12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH1BlockEntity> MOSAIC_H1_BLOCK_ENTITY = register("h1", MosaicH1BlockEntity::new, ModBlocks.MOSAIC_H1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH2BlockEntity> MOSAIC_H2_BLOCK_ENTITY = register("h2", MosaicH2BlockEntity::new, ModBlocks.MOSAIC_H2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH3BlockEntity> MOSAIC_H3_BLOCK_ENTITY = register("h3", MosaicH3BlockEntity::new, ModBlocks.MOSAIC_H3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH4BlockEntity> MOSAIC_H4_BLOCK_ENTITY = register("h4", MosaicH4BlockEntity::new, ModBlocks.MOSAIC_H4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH5BlockEntity> MOSAIC_H5_BLOCK_ENTITY = register("h5", MosaicH5BlockEntity::new, ModBlocks.MOSAIC_H5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH6BlockEntity> MOSAIC_H6_BLOCK_ENTITY = register("h6", MosaicH6BlockEntity::new, ModBlocks.MOSAIC_H6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH7BlockEntity> MOSAIC_H7_BLOCK_ENTITY = register("h7", MosaicH7BlockEntity::new, ModBlocks.MOSAIC_H7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH8BlockEntity> MOSAIC_H8_BLOCK_ENTITY = register("h8", MosaicH8BlockEntity::new, ModBlocks.MOSAIC_H8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH9BlockEntity> MOSAIC_H9_BLOCK_ENTITY = register("h9", MosaicH9BlockEntity::new, ModBlocks.MOSAIC_H9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH10BlockEntity> MOSAIC_H10_BLOCK_ENTITY = register("h10", MosaicH10BlockEntity::new, ModBlocks.MOSAIC_H10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH11BlockEntity> MOSAIC_H11_BLOCK_ENTITY = register("h11", MosaicH11BlockEntity::new, ModBlocks.MOSAIC_H11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicH12BlockEntity> MOSAIC_H12_BLOCK_ENTITY = register("h12", MosaicH12BlockEntity::new, ModBlocks.MOSAIC_H12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI1BlockEntity> MOSAIC_I1_BLOCK_ENTITY = register("i1", MosaicI1BlockEntity::new, ModBlocks.MOSAIC_I1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI2BlockEntity> MOSAIC_I2_BLOCK_ENTITY = register("i2", MosaicI2BlockEntity::new, ModBlocks.MOSAIC_I2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI3BlockEntity> MOSAIC_I3_BLOCK_ENTITY = register("i3", MosaicI3BlockEntity::new, ModBlocks.MOSAIC_I3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI4BlockEntity> MOSAIC_I4_BLOCK_ENTITY = register("i4", MosaicI4BlockEntity::new, ModBlocks.MOSAIC_I4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI5BlockEntity> MOSAIC_I5_BLOCK_ENTITY = register("i5", MosaicI5BlockEntity::new, ModBlocks.MOSAIC_I5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI6BlockEntity> MOSAIC_I6_BLOCK_ENTITY = register("i6", MosaicI6BlockEntity::new, ModBlocks.MOSAIC_I6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI7BlockEntity> MOSAIC_I7_BLOCK_ENTITY = register("i7", MosaicI7BlockEntity::new, ModBlocks.MOSAIC_I7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI8BlockEntity> MOSAIC_I8_BLOCK_ENTITY = register("i8", MosaicI8BlockEntity::new, ModBlocks.MOSAIC_I8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI9BlockEntity> MOSAIC_I9_BLOCK_ENTITY = register("i9", MosaicI9BlockEntity::new, ModBlocks.MOSAIC_I9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI10BlockEntity> MOSAIC_I10_BLOCK_ENTITY = register("i10", MosaicI10BlockEntity::new, ModBlocks.MOSAIC_I10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI11BlockEntity> MOSAIC_I11_BLOCK_ENTITY = register("i11", MosaicI11BlockEntity::new, ModBlocks.MOSAIC_I11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicI12BlockEntity> MOSAIC_I12_BLOCK_ENTITY = register("i12", MosaicI12BlockEntity::new, ModBlocks.MOSAIC_I12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ1BlockEntity> MOSAIC_J1_BLOCK_ENTITY = register("j1", MosaicJ1BlockEntity::new, ModBlocks.MOSAIC_J1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ2BlockEntity> MOSAIC_J2_BLOCK_ENTITY = register("j2", MosaicJ2BlockEntity::new, ModBlocks.MOSAIC_J2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ3BlockEntity> MOSAIC_J3_BLOCK_ENTITY = register("j3", MosaicJ3BlockEntity::new, ModBlocks.MOSAIC_J3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ4BlockEntity> MOSAIC_J4_BLOCK_ENTITY = register("j4", MosaicJ4BlockEntity::new, ModBlocks.MOSAIC_J4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ5BlockEntity> MOSAIC_J5_BLOCK_ENTITY = register("j5", MosaicJ5BlockEntity::new, ModBlocks.MOSAIC_J5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ6BlockEntity> MOSAIC_J6_BLOCK_ENTITY = register("j6", MosaicJ6BlockEntity::new, ModBlocks.MOSAIC_J6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ7BlockEntity> MOSAIC_J7_BLOCK_ENTITY = register("j7", MosaicJ7BlockEntity::new, ModBlocks.MOSAIC_J7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ8BlockEntity> MOSAIC_J8_BLOCK_ENTITY = register("j8", MosaicJ8BlockEntity::new, ModBlocks.MOSAIC_J8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ9BlockEntity> MOSAIC_J9_BLOCK_ENTITY = register("j9", MosaicJ9BlockEntity::new, ModBlocks.MOSAIC_J9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ10BlockEntity> MOSAIC_J10_BLOCK_ENTITY = register("j10", MosaicJ10BlockEntity::new, ModBlocks.MOSAIC_J10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ11BlockEntity> MOSAIC_J11_BLOCK_ENTITY = register("j11", MosaicJ11BlockEntity::new, ModBlocks.MOSAIC_J11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicJ12BlockEntity> MOSAIC_J12_BLOCK_ENTITY = register("j12", MosaicJ12BlockEntity::new, ModBlocks.MOSAIC_J12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK1BlockEntity> MOSAIC_K1_BLOCK_ENTITY = register("k1", MosaicK1BlockEntity::new, ModBlocks.MOSAIC_K1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK2BlockEntity> MOSAIC_K2_BLOCK_ENTITY = register("k2", MosaicK2BlockEntity::new, ModBlocks.MOSAIC_K2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK3BlockEntity> MOSAIC_K3_BLOCK_ENTITY = register("k3", MosaicK3BlockEntity::new, ModBlocks.MOSAIC_K3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK4BlockEntity> MOSAIC_K4_BLOCK_ENTITY = register("k4", MosaicK4BlockEntity::new, ModBlocks.MOSAIC_K4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK5BlockEntity> MOSAIC_K5_BLOCK_ENTITY = register("k5", MosaicK5BlockEntity::new, ModBlocks.MOSAIC_K5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK6BlockEntity> MOSAIC_K6_BLOCK_ENTITY = register("k6", MosaicK6BlockEntity::new, ModBlocks.MOSAIC_K6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK7BlockEntity> MOSAIC_K7_BLOCK_ENTITY = register("k7", MosaicK7BlockEntity::new, ModBlocks.MOSAIC_K7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK8BlockEntity> MOSAIC_K8_BLOCK_ENTITY = register("k8", MosaicK8BlockEntity::new, ModBlocks.MOSAIC_K8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK9BlockEntity> MOSAIC_K9_BLOCK_ENTITY = register("k9", MosaicK9BlockEntity::new, ModBlocks.MOSAIC_K9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK10BlockEntity> MOSAIC_K10_BLOCK_ENTITY = register("k10", MosaicK10BlockEntity::new, ModBlocks.MOSAIC_K10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK11BlockEntity> MOSAIC_K11_BLOCK_ENTITY = register("k11", MosaicK11BlockEntity::new, ModBlocks.MOSAIC_K11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicK12BlockEntity> MOSAIC_K12_BLOCK_ENTITY = register("k12", MosaicK12BlockEntity::new, ModBlocks.MOSAIC_K12_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL1BlockEntity> MOSAIC_L1_BLOCK_ENTITY = register("l1", MosaicL1BlockEntity::new, ModBlocks.MOSAIC_L1_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL2BlockEntity> MOSAIC_L2_BLOCK_ENTITY = register("l2", MosaicL2BlockEntity::new, ModBlocks.MOSAIC_L2_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL3BlockEntity> MOSAIC_L3_BLOCK_ENTITY = register("l3", MosaicL3BlockEntity::new, ModBlocks.MOSAIC_L3_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL4BlockEntity> MOSAIC_L4_BLOCK_ENTITY = register("l4", MosaicL4BlockEntity::new, ModBlocks.MOSAIC_L4_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL5BlockEntity> MOSAIC_L5_BLOCK_ENTITY = register("l5", MosaicL5BlockEntity::new, ModBlocks.MOSAIC_L5_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL6BlockEntity> MOSAIC_L6_BLOCK_ENTITY = register("l6", MosaicL6BlockEntity::new, ModBlocks.MOSAIC_L6_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL7BlockEntity> MOSAIC_L7_BLOCK_ENTITY = register("l7", MosaicL7BlockEntity::new, ModBlocks.MOSAIC_L7_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL8BlockEntity> MOSAIC_L8_BLOCK_ENTITY = register("l8", MosaicL8BlockEntity::new, ModBlocks.MOSAIC_L8_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL9BlockEntity> MOSAIC_L9_BLOCK_ENTITY = register("l9", MosaicL9BlockEntity::new, ModBlocks.MOSAIC_L9_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL10BlockEntity> MOSAIC_L10_BLOCK_ENTITY = register("l10", MosaicL10BlockEntity::new, ModBlocks.MOSAIC_L10_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL11BlockEntity> MOSAIC_L11_BLOCK_ENTITY = register("l11", MosaicL11BlockEntity::new, ModBlocks.MOSAIC_L11_BLOCK);
    public static final BlockEntityType<@NotNull MosaicL12BlockEntity> MOSAIC_L12_BLOCK_ENTITY = register("l12", MosaicL12BlockEntity::new, ModBlocks.MOSAIC_L12_BLOCK);
    //:::::::::::

}
